name: Data Pipeline Practice

on:
  schedule:
    - cron: '*/5 * * * *' 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch API and Update JSON
        run: |
          CURRENT_MIN=$(date +%M)
          TARGET_ID=$((10#$CURRENT_MIN + 1))
          URL="https://jsonplaceholder.typicode.com/todos/$TARGET_ID"
          
          FILE_NAME="soohyuk_test.json"
          
          echo "Fetching data from: $URL"
          curl -s $URL >> $FILE_NAME

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase
          git add .
          git commit -m "data: update $FILE_NAME with ID $TARGET_ID"
          git push
